"""empty message

Revision ID: 1e866fd6eff9
Revises: 6366ffea921e
Create Date: 2023-08-15 02:18:40.443240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e866fd6eff9'
down_revision = '6366ffea921e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint('pet_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pet_ibfk_3', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('bills_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bills_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('pet_ibfk_3', 'my_bills', ['bills_id'], ['bills_id'])
        batch_op.create_foreign_key('pet_ibfk_2', 'pet_owner', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
