"""empty message

Revision ID: 2031621929ba
Revises: 
Create Date: 2023-08-27 21:13:31.352181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031621929ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('appointment_comments', sa.String(length=200), nullable=True),
    sa.Column('appointment_status', sa.Enum('Accepted', 'Rejected', 'Pending', 'In-progress'), server_default='In-progress', nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['vet.vet_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
