"""empty message

Revision ID: 6366ffea921e
Revises: 83fd398bf330
Create Date: 2023-08-15 00:55:11.882330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6366ffea921e'
down_revision = '83fd398bf330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bills_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'my_bills', ['bills_id'], ['bills_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bills_id')

    # ### end Alembic commands ###
