"""empty message

Revision ID: 83fd398bf330
Revises: 
Create Date: 2023-08-15 00:52:00.651924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fd398bf330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('pet_owner',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fullname', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_pwd', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vet',
    sa.Column('vet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vet_fullname', sa.String(length=100), nullable=False),
    sa.Column('vet_email', sa.String(length=120), nullable=True),
    sa.Column('vet_pwd', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('vet_id')
    )
    op.create_table('my_bills',
    sa.Column('bills_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bills_date', sa.DateTime(), nullable=True),
    sa.Column('bills_status', sa.Enum('pending', 'failed', 'paid'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pet_owner.user_id'], ),
    sa.PrimaryKeyConstraint('bills_id')
    )
    op.create_table('pet',
    sa.Column('pet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_cat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=50), nullable=False),
    sa.Column('pet_descript', sa.Text(), nullable=True),
    sa.Column('pet_pic', sa.String(length=100), nullable=True),
    sa.Column('pet_gender', sa.Enum('male', 'female'), server_default='female', nullable=False),
    sa.Column('pet_color', sa.String(length=10), nullable=False),
    sa.Column('pet_weight_at_reg', sa.Float(), nullable=True),
    sa.Column('pet_dob', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_cat_id'], ['category.cat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pet_owner.user_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('diagnosis',
    sa.Column('pet_diagnosis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('pet_diagnosis_id')
    )
    op.create_table('food_type',
    sa.Column('food_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('food_discription', sa.String(length=100), nullable=False),
    sa.Column('food_nutritious_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('food_type_id')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_amt', sa.Float(), nullable=False),
    sa.Column('bills_id', sa.Integer(), nullable=False),
    sa.Column('pay_refno', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'failed', 'paid'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['bills_id'], ['my_bills.bills_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_table('pet_breed',
    sa.Column('pet_breed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_breed_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('pet_breed_id')
    )
    op.create_table('pet_medical_record',
    sa.Column('Pet_medical_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_current_weight', sa.Integer(), nullable=True),
    sa.Column('pet_vaccination_status', sa.String(length=10), nullable=False),
    sa.Column('pet_last_visit_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('Pet_medical_record_id')
    )
    op.create_table('diagnosis_treatment',
    sa.Column('diagnosis_treatment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_treatment', sa.String(length=200), nullable=False),
    sa.Column('vet_comment', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_diagnosis_id'], ['diagnosis.pet_diagnosis_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_treatment_id')
    )
    op.create_table('pet_feeding',
    sa.Column('Pet_feeding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_food_type_id', sa.Integer(), nullable=False),
    sa.Column('pet_feeding_time', sa.DateTime(), nullable=True),
    sa.Column('pet_feeding_quantity', sa.Float(), nullable=True),
    sa.Column('pet_feeding_note', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_food_type_id'], ['food_type.food_type_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('Pet_feeding_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_feeding')
    op.drop_table('diagnosis_treatment')
    op.drop_table('pet_medical_record')
    op.drop_table('pet_breed')
    op.drop_table('payment')
    op.drop_table('food_type')
    op.drop_table('diagnosis')
    op.drop_table('pet')
    op.drop_table('my_bills')
    op.drop_table('vet')
    op.drop_table('pet_owner')
    op.drop_table('category')
    # ### end Alembic commands ###
