"""empty message

Revision ID: eaa9f4dce171
Revises: 01cae9d70439
Create Date: 2023-09-09 22:56:43.814059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaa9f4dce171'
down_revision = '01cae9d70439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_ref_no', sa.Integer(), nullable=False))
        batch_op.drop_column('pay_refno')
        batch_op.drop_column('pay_status')
        batch_op.drop_column('pay_amt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_amt', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('pay_status', mysql.ENUM('Pending', 'Failed', 'Paid'), server_default=sa.text("'Pending'"), nullable=False))
        batch_op.add_column(sa.Column('pay_refno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('paystack_ref_no')

    # ### end Alembic commands ###
