"""empty message

Revision ID: f847b4cfa96a
Revises: bfe84dac2923
Create Date: 2023-09-17 10:53:33.209996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f847b4cfa96a'
down_revision = 'bfe84dac2923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_likes', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pet_dislikes', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pet_comments', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('pet_comments')
        batch_op.drop_column('pet_dislikes')
        batch_op.drop_column('pet_likes')

    # ### end Alembic commands ###
